### ISSUE TITLE
Transfer to SR namespace.

### ISSUE THREAD

**Issue by robfrawley** [scribenet/nginx-servats-module#3]
@dcorrigan, @andrewhthomas, @drech: Unless you guys intend to continue development of this, can we transfer this repository to the [src-run](https://github.com/src-run) organization (allows for me to retain issues, forks, stars, watchers, etc).

Please advise if there is any friction to doing so. Otherwise, if there is no issue with this, @dcorrigan or @andrewhthomas, please transfer (obviously I cannot do so anymore).

**Comment by dcorrigan** [comment]
We can't transfer to an org we're not admins of, and I can't transfer to you because you already have a fork. If you delete or rename the fork I can transfer it to you, then you to src-run.

**Comment by robfrawley** [comment]
@dcorrigan I removed the fork from my personal account, so you should be able to transfer it now. Let me  know if either you or @andrewhthomas want to be added as collaborators on the repo (gives you member level access, allowing pushes and what-not). Thanks for the quick response!

**Comment by dcorrigan** [comment]
To me, then to you, then to src-run.

**Comment by robfrawley** [comment]
Thanks!
